CREATE TABLE CUSTOMERS
(
    CUSTOMER_ID     NUMBER(6)        NULL,
    CUST_FIRST_NAME VARCHAR2(20) NOT NULL,
    CUST_LAST_NAME  VARCHAR2(20) NOT NULL,
    NLS_LANGUAGE    VARCHAR2(3)      NULL,
    NLS_TERRITORY   VARCHAR2(30)     NULL,
    CREDIT_LIMIT    NUMBER(9,2)      NULL,
    CUST_EMAIL      VARCHAR2(30)     NULL,
    ACCOUNT_MGR_ID  NUMBER(6)        NULL
);
CREATE TABLE ORDERS
(
    ORDER_ID     NUMBER(12)      NULL,
    ORDER_DATE   DATE        NOT NULL,
    ORDER_MODE   VARCHAR2(8)     NULL,
    CUSTOMER_ID  NUMBER(6)   NOT NULL,
    ORDER_STATUS NUMBER(2)       NULL,
    ORDER_TOTAL  NUMBER(8,2)     NULL,
    SALES_REP_ID NUMBER(6)       NULL,
    PROMOTION_ID NUMBER(6)       NULL
);
CREATE TABLE INVENTORIES
(
    PRODUCT_ID       NUMBER(6)     NULL,
    WAREHOUSE_ID     NUMBER(3) NOT NULL,
    QUANTITY_ON_HAND NUMBER(8) NOT NULL
);
CREATE TABLE ORDER_ITEMS
(
    ORDER_ID     NUMBER(12)      NULL,
    LINE_ITEM_ID NUMBER(3)   NOT NULL,
    PRODUCT_ID   NUMBER(6)   NOT NULL,
    UNIT_PRICE   NUMBER(8,2)     NULL,
    QUANTITY     NUMBER(8)       NULL
);
CREATE TABLE PRODUCT_DESCRIPTIONS
(
    PRODUCT_ID             NUMBER(6)           NULL,
    LANGUAGE_ID            VARCHAR2(3)         NULL,
    TRANSLATED_NAME        NVARCHAR2(50)   NOT NULL,
    TRANSLATED_DESCRIPTION NVARCHAR2(2000) NOT NULL
);
CREATE TABLE PRODUCT_INFORMATION
(
    PRODUCT_ID          NUMBER(6)          NULL,
    PRODUCT_NAME        VARCHAR2(50)       NULL,
    PRODUCT_DESCRIPTION VARCHAR2(2000)     NULL,
    CATEGORY_ID         NUMBER(2)          NULL,
    WEIGHT_CLASS        NUMBER(1)          NULL,
    SUPPLIER_ID         NUMBER(6)          NULL,
    PRODUCT_STATUS      VARCHAR2(20)       NULL,
    LIST_PRICE          NUMBER(8,2)        NULL,
    MIN_PRICE           NUMBER(8,2)        NULL,
    CATALOG_URL         VARCHAR2(50)       NULL
);

